eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
server.port=8081
spring.application.name=api-gateway

logging.level.root=INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator=INFO
logging.level.org.springframework.cloud.gateway=DEBUG

jwt.secret=b8fFzXrE7sW9tY2vQ1uK9rM5cT8hN0aPvQ7yXrD4eP9zW3uL2nK5sT6rQ9aY0xNc

#Discovery Server Route
spring.cloud.gateway.routes[0].id=discovery-server
spring.cloud.gateway.routes[0].uri=http://localhost:8761
spring.cloud.gateway.routes[0].predicates[0]=Path=/eureka/web
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/eureka/(?<segment>.*), /
#spring.cloud.gateway.routes[0].filters[0]=SetPath=/

#Discovery Server Static Resource Route
spring.cloud.gateway.routes[1].id=discovery-server-static
spring.cloud.gateway.routes[1].uri=http://localhost:8761
spring.cloud.gateway.routes[1].predicates[0]=Path=/eureka/**

#Account Service Route
spring.cloud.gateway.routes[2].id=account-service
spring.cloud.gateway.routes[2].uri=lb://ACCOUNT-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/accounts/**,/account/v3/api-docs/**
spring.cloud.gateway.routes[2].filters[0]=Authentication

#Transaction Service Route
spring.cloud.gateway.routes[3].id=transaction-service
spring.cloud.gateway.routes[3].uri=lb://TRANSACTION-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/transactions/**,/api/dashboard/**,/api/reports/**,/transaction/v3/api-docs/**
spring.cloud.gateway.routes[3].filters[0]=Authentication

#user-service Route
spring.cloud.gateway.routes[4].id=user-service
spring.cloud.gateway.routes[4].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/auth/**,/user/v3/api-docs/**

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Swagger UI - Aggregate Multiple Microservices

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# Optional: custom path (you can skip this)
springdoc.swagger-ui.path=/swagger-ui/index.html

# Register microservices in Swagger UI

springdoc.swagger-ui.urls[0].name=account-service
springdoc.swagger-ui.urls[0].url=/account/v3/api-docs

springdoc.swagger-ui.urls[1].name=user-service
springdoc.swagger-ui.urls[1].url=/user/v3/api-docs

# (Add more services like this)
springdoc.swagger-ui.urls[2].name=transaction-service
springdoc.swagger-ui.urls[2].url=/transaction/v3/api-docs
