server.port = 8082
spring.application.name=user-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
springdoc.api-docs.path=/user/v3/api-docs

jwt.secret=b8fFzXrE7sW9tY2vQ1uK9rM5cT8hN0aPvQ7yXrD4eP9zW3uL2nK5sT6rQ9aY0xNc
jwt.expiration=86400000

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=system
spring.datasource.password=tiger1
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=create-drop  
